name: PlatformIO CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: actions/setup-node@v4

      - name: Install npm packages
        run: cd scripts && npm install && cd ..

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project
        run: pio run

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware.bin
          path: |
            .pio/build/esp12/firmware.bin
      - name: Release with Notes
        uses: softprops/action-gh-release@v1
        with:
          files: |
            .pio/build/esp12/firmware.bin
          tag_name: "V3.0.0"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}